services:
  mongodb:
    image: mongo:latest
    container_name: pokedexDB
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
      - ./mongo-seed:/docker-entrypoint-initdb.d

volumes:
  mongodb_data:
